### ISSUE TITLE
'AxisOption' object has no attribute 'prepare'

### ISSUE THREAD

**Issue by karl-tran-2002** [Haoming02/sd-webui-advanced-xyz#1]
File "/base/stable-diffusion-v152/stable-diffusion-webui/extensions/sd-webui-advanced-xyz/scripts/adv_xyz_ui.py", line 236, in process_axis
        elif opt.prepare is not None:
    AttributeError: 'AxisOption' object has no attribute 'prepare'

**Comment by Haoming02** [comment]
> v152

Assuming this meant you're using an old version of the Webui, can you try with new version first?

**Comment by karl-tran-2002** [comment]
I cannot update to the latest version because I must use version 1.5.2, which is the same as the one my company is using.

**Comment by Haoming02** [comment]
Then sorry, I probably won't backport this Extension, since I just want to use the built-in code as much as possible...

**Comment by karl-tran-2002** [comment]
okay, thank you for your support
